# 영화 조회순 크롤링

In [ ]:
import urllib.request as req   # as 별명  //별명으로 사용
from bs4 import BeautifulSoup as bs

In [ ]:
url = 'https://movie.naver.com/movie/sdb/rank/rmovie.nhn?sel=cur&date=20210712'
# site = urllib.request.urlopen(url)
response = req.urlopen(url)
response  # 네이버 영화 평점 퍼올 객체 생성

soup = bs(response,"html.parser") 
# 네이버 영화평점 사이트에서 내가 원하는 정보를 꺼내는 객체 __parser// 생성
soup

In [ ]:
title = soup.find_all("td",{'class' : 'title'})
for i in title:
  print(i.text.replace("\n",''))
print("="*100)
title = soup.find_all("div",{"class" : "tit5"})

for i in title:
  print(i.text.replace("\n",''))

print("=" * 100)

for i in title:
  print(i.find('a').text)

In [ ]:
title = soup.find_all("div",{"class" : "tit5"})
rank = soup.find_all("td",{"class" : "point"})

In [ ]:
for title, rank in zip(title,rank):
  print("영화제목 {}  평점  {} ".format(title.find('a').text, rank.text))

In [ ]:
for title, point in zip(title,rank):
  print(" = " * 100)
  print("title.text,strip() = ",title.text.strip())
  print("title.find('a')['href']= ",title.find('a')['href'])
  print("point = ", point.text)

# 날씨데이터 크롤링

In [ ]:
import requests
from bs4 import BeautifulSoup as bs

In [2]:
response = requests.get('http://www.weather.go.kr/weather/observation/currentweather.jsp')
# 기상청 사이트 내용 가져옴
# response 200 : 가져오기 성공
# response 404 : 없는 URL
# response 500, 505 : 서버 다운 
# request는 urllib 처럼 한번 read하고 삭제 안되고 객체 계쏙 들고있음

In [ ]:
response.content

In [ ]:
response.text

In [ ]:
soup = bs(response.text,'html.parser')

table = soup.find("table", {"class": "table_develop3"})

for tr in table.find_all('tr'):
  print("="*100)
  print(tr)
  print("="*100)

In [ ]:
for tr in table.findAll("tr"):
  print("="*100)
  print("tr")
  print("="*100)
  print(tr)
  print("="*100)
  print("tr.find('a') = " ,tr.find('a'))

  if tr.find('a'):
    print("tr.find('a').text = " ,tr.find('a').text)
  print("=" * 100)

In [ ]:
for tr in table.findAll("tr"):
  print("="*100)
  print("$" * 100)
  print(tr)
  print("$" * 100)

  if tr.find('a'):
    print("tr.find('a').text = ", tr.find('a').text)
    print('tr.findAll("td")[5]=',tr.findAll("td")[5])
    print('tr.findAll("td")[10]=',tr.findAll("td")[9])  
 
  print("="*100)

In [ ]:
data = []
for tr in table.findAll('tr'):
  if tr.find('a'):
    data.append([tr.find("a").text, tr.findAll("td")[5].text,tr.findAll("td")[9].text])
data

In [ ]:
with open("weather.csv",'w') as file:
  file.write("point,temperature,humidity")

In [ ]:
for point, temperature,humidity in data:
  print("point = ", point)
  print("temperature = ", temperature)
  print("humidity = ", humiditiy)
  print("="*100)

In [ ]:
# 현준

In [ ]:
with open("weather.csv",'w') as file:
  for point,temp,humi in data:
    file.write("{},{},{}".format(point,temp,humi))

=====================

In [4]:
import requests
from bs4 import BeautifulSoup as bs
soup = bs(response.text,'html.parser')

table = soup.find("table", {"class": "table_develop3"})
data = []
for tr in table.findAll('tr'):
  if tr.find('a'):
    data.append([tr.find("a").text, tr.findAll("td")[5].text,tr.findAll("td")[9].text])

with open("weather.csv","w") as file:

  file.write("point,temperature,humidity\n")
# for point, temp, humi in data:
#   print("point = ", point)
#   print("temperature = ", temp)
#   print("humidity = ", humi)
#   print("="*100)
print(data)

with open("weather.csv",'a') as file:
  for point,temp,humi in data:
    file.write("{},{},{}\n".format(point,temp,humi))

[['강릉', '26.2', '84'], ['강진군', '25.6', '77'], ['강화', '26.0', '89'], ['거제', '26.6', '79'], ['거창', '24.0', '94'], ['경주시', '24.5', '91'], ['고산', '28.6', '67'], ['고창', '25.5', '84'], ['고창군', '25.4', '81'], ['고흥', '25.2', '74'], ['광양시', '26.9', '69'], ['광주', '27.6', '76'], ['구미', '26.0', '74'], ['군산', '26.7', '92'], ['금산', '25.2', '86'], ['김해시', '26.3', '77'], ['남원', '24.7', '85'], ['남해', '24.2', '86'], ['대관령', '17.2', '90'], ['대구', '26.6', '67'], ['대전', '29.1', '74'], ['동두천', '26.5', '80'], ['동해', '23.9', '99'], ['목포', '27.7', '66'], ['문경', '24.2', '91'], ['밀양', '26.3', '77'], ['백령도', '25.3', '74'], ['보령', '27.2', '79'], ['보성군', '24.4', '93'], ['보은', '23.6', '95'], ['봉화', '20.4', '98'], ['부산', '26.5', '82'], ['부안', '26.5', '85'], ['부여', '26.5', '85'], ['북강릉', '23.4', '97'], ['북창원', '27.2', '77'], ['북춘천', '27.1', '86'], ['산청', '24.4', '93'], ['상주', '25.1', '88'], ['서귀포', '26.8', '88'], ['서산', '25.6', '81'], ['서울', '30.7', '55'], ['성산', '27.2', '92'], ['세종', '27.9', '69'], ['속초', '24.6', '91'], ['수원', '27.9', '84'], ['순창군', '25.1', '90'], ['순천', '22.8', '95'], ['안동', '25.7', '79'], ['양산시', '26.7', '83'], ['양평', '25.9', '81'], ['여수', '27.7', '69'], ['영광군', '25.7', '84'], ['영덕', '23.3', '95'], ['영월', '24.2', '86'], ['영주', '23.1', '92'], ['영천', '23.7', '86'], ['완도', '25.0', '80'], ['울릉도', '24.3', '90'], ['울산', '26.1', '91'], ['울진', '23.7', '97'], ['원주', '27.1', '66'], ['의령군', '24.5', '92'], ['의성', '23.4', '91'], ['이천', '25.5', '86'], ['인제', '24.0', '77'], ['인천', '28.6', '62'], ['임실', '23.1', '95'], ['장수', '22.4', '97'], ['장흥', '23.9', '82'], ['전주', '27.0', '73'], ['정선군', '23.0', '86'], ['정읍', '25.6', '80'], ['제주', '27.0', '84'], ['제천', '23.5', '95'], ['진도군', '23.9', '83'], ['진주', '23.6', '94'], ['창원', '27.8', '63'], ['천안', '24.9', '91'], ['철원', '25.7', '99'], ['청송군', '21.9', '83'], ['청주', '29.6', '67'], ['추풍령', '24.9', '74'], ['춘천', '27.9', '83'], ['충주', '26.0', '82'], ['태백', '21.0', '95'], ['통영', '27.0', '75'], ['파주', '25.2', '96'], ['포항', '26.8', '85'], ['함양군', '24.0', '92'], ['합천', '24.5', '96'], ['해남', '26.4', '69'], ['홍성', '27.0', '82'], ['홍천', '26.0', '81'], ['흑산도', '26.8', '81']]

In [ ]:
import pandas as pd
# panda 본명대신 별명 pd 사용
pd.read_csv("weather.csv")

df = pd.read_csv("weather.csv")
# pd의 read_csv 기능을 사용하여 "weather.csv" 불러오기


df["point"] == "합천"
# point 줄이 합천이면 True  ,, 아니면 False

df[ df["point"] == "합천" ]
# df["point"] == "합천" : point칸에 저장된 값이 "합천"인 줄  , 조건 일치true , 아니면 false

df["point"].isin(["강릉","흑산도","합천"])
# point가 "강릉" ,"흑산도" ,"합천"이면 True  , 아니면 False

df [df["point"].isin(["강릉","흑산도","합천"])]
# point가 "강릉" ,"흑산도" ,"합천"이면 True  , 아니면 False로 나눠서
# True인것(강릉,흑산도,합천) 으로 df 생성   (df는 Data Frame으로 그냥 테이블(표) 같은것!)

df [  df["point"].isin( ["서울","인천","수원","대전","대구","광주","부산","울산"] ) ]
# 위와 동일
# point가 ["서울","인천","수원","대전","대구","광주","부산","울산"]이면  df생성

df = df.set_index("point")
# point 칸을 index로 설정  *@@@@@@*
# point칸에 저장된 값은 loc 함수로 쉽게 검색 가능

df.loc[["서울","대전","인천"]] 
# 위에서 isin보다 간편하게 검색 할수있음

df["humidity"].isin([70, 74 ,80])
# humidity칸에 저장된 값이 70, 74 ,80 인 줄 조건 만족하면 True, 아니면 False

df[df["humidity"].isin([70, 74 ,80])]
df = df.reset_index()  
# 기존 인덱스 point 취소 ,,,즉 3줄쯤 위에 *@@@@@*에 point로 설정한거 초기화

df = df.set_index("humidity")
# humidity칸을 index로 설정

In [ ]:
df.loc[90]

point            울진
temperature    25.6
Name: 90, dtype: object

In [ ]:
pd.read_csv("weather.csv",index_col = 'point')
# weather.csv 읽으면서 point칸을 인덱스로 설정
df = pd.read_csv("weather.csv", index_col = "point")

In [ ]:
df.loc[["서울","부산"]]
city_df = df.loc[["서울","인천","대전","대구","광주","부산"]]
city_df

       temperature  humidity
point
서울            29.4        70
인천            29.7        55
대전            32.1        61
대구            30.4        53
광주            29.9        71
부산            27.6        85